default: &default
  adapter: postgresql
  encoding: unicode
  username : rails
  password: 1234
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hellorails_test

test:
  <<: *default
  database: hellorails_test

production:
  <<: *default
  database: hellorails_test
  username: hellorails
  password: <%= ENV["HELLORAILS_DATABASE_PASSWORD"] %>
